<?xml version="1.0" encoding="UTF-8"?>
<!--
 Web Services API : CaseWebService
-->
<definitions targetNamespace="http://soap.sforce.com/schemas/class/CaseWebService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://soap.sforce.com/schemas/class/CaseWebService">
 <types>
  <xsd:schema elementFormDefault="qualified" targetNamespace="http://soap.sforce.com/schemas/class/CaseWebService">
   <xsd:element name="AllowFieldTruncationHeader">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="allowFieldTruncation" type="xsd:boolean"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="CallOptions">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="client" type="xsd:string"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="DebuggingHeader">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="categories" minOccurs="0" maxOccurs="unbounded" type="tns:LogInfo"/>
      <xsd:element name="debugLevel" type="tns:LogType"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:complexType name="LogInfo">
    <xsd:sequence>
     <xsd:element name="category" type="tns:LogCategory"/>
     <xsd:element name="level" type="tns:LogCategoryLevel"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:simpleType name="LogCategory">
    <xsd:restriction base="xsd:string">
     <xsd:enumeration value="Db"/>
     <xsd:enumeration value="Workflow"/>
     <xsd:enumeration value="Validation"/>
     <xsd:enumeration value="Callout"/>
     <xsd:enumeration value="Apex_code"/>
     <xsd:enumeration value="Apex_profiling"/>
     <xsd:enumeration value="Visualforce"/>
     <xsd:enumeration value="System"/>
     <xsd:enumeration value="Wave"/>
     <xsd:enumeration value="Nba"/>
     <xsd:enumeration value="All"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="LogCategoryLevel">
    <xsd:restriction base="xsd:string">
     <xsd:enumeration value="None"/>
     <xsd:enumeration value="Finest"/>
     <xsd:enumeration value="Finer"/>
     <xsd:enumeration value="Fine"/>
     <xsd:enumeration value="Debug"/>
     <xsd:enumeration value="Info"/>
     <xsd:enumeration value="Warn"/>
     <xsd:enumeration value="Error"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="LogType">
    <xsd:restriction base="xsd:string">
     <xsd:enumeration value="None"/>
     <xsd:enumeration value="Debugonly"/>
     <xsd:enumeration value="Db"/>
     <xsd:enumeration value="Profiling"/>
     <xsd:enumeration value="Callout"/>
     <xsd:enumeration value="Detail"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:element name="DebuggingInfo">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="debugLog" type="xsd:string"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="SessionHeader">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="sessionId" type="xsd:string"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:simpleType name="ID">
    <xsd:restriction base="xsd:string">
     <xsd:length value="18"/>
     <xsd:pattern value="[a-zA-Z0-9]{18}"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:complexType name="attachmnt">
    <xsd:sequence>
     <xsd:element name="body" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Description" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="length" minOccurs="0" type="xsd:int" nillable="true"/>
     <xsd:element name="Name" minOccurs="0" type="xsd:string" nillable="true"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="caseRequestWrapper">
    <xsd:sequence>
     <xsd:element name="altcontphonenum" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="amount" minOccurs="0" type="xsd:int" nillable="true"/>
     <xsd:element name="attachments" minOccurs="0" maxOccurs="unbounded" type="tns:attachmnt" nillable="true"/>
     <xsd:element name="Attorneycontactnum" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Attorneyname" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="BankruptcyCaseNumber" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="BankruptcyCourtNumber" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Bankruptcyfininstn" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="BankruptcyLocation" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="casefilename" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="checkendnum" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="checkstartnum" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="chkdisputes" minOccurs="0" maxOccurs="unbounded" type="tns:checkDispute" nillable="true"/>
     <xsd:element name="City" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Comments" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="ConsumerFirstNameBusinessNam" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="ConsumerLastName" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="ConsumerMiddleName" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="ConsumerPhoneNumber" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="description" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="DetailedIdCategory1" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="DetailedIdCategory3" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="emailaddress" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="FinancialInst" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="idcode" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="IDNumber1" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="IDNumber2" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="IDNumber3" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="IDNumber4" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="infodisputes" minOccurs="0" maxOccurs="unbounded" type="tns:infoDispute" nillable="true"/>
     <xsd:element name="JointAccholderfirstname" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="JointAccholderlastname" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="JointDetailedIdCategory1" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="JointIDNumber1" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="JointIDNumber2" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="JointIDNumber3" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="JointIDNumber4" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="LegalSelopt1" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="LegalSelopt2" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="NoticeDate" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="preferredContact" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="ProblemCategory" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Referencenumber" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Routingnumber" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="State" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="StreetAddress" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="SubCategory" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="ZipCode" minOccurs="0" type="xsd:string" nillable="true"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="caseResponseWrapper">
    <xsd:sequence>
     <xsd:element name="ReturnCode" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="ReturnMsg" minOccurs="0" type="xsd:string" nillable="true"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="checkDispute">
    <xsd:sequence>
     <xsd:element name="CheckAmount" minOccurs="0" type="xsd:double" nillable="true"/>
     <xsd:element name="Checkdate" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Checknumber" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="CheckPayableTo" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Comments" minOccurs="0" type="xsd:string" nillable="true"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="infoDispute">
    <xsd:sequence>
     <xsd:element name="code" minOccurs="0" type="xsd:string" nillable="true"/>
     <xsd:element name="Name" minOccurs="0" type="xsd:string" nillable="true"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="address">
    <xsd:complexContent>
     <xsd:extension base="tns:location">
      <xsd:sequence>
       <xsd:element name="city" type="xsd:string"/>
       <xsd:element name="country" type="xsd:string"/>
       <xsd:element name="countryCode" type="xsd:string"/>
       <xsd:element name="geocodeAccuracy" type="xsd:string"/>
       <xsd:element name="postalCode" type="xsd:string"/>
       <xsd:element name="state" type="xsd:string"/>
       <xsd:element name="stateCode" type="xsd:string"/>
       <xsd:element name="street" type="xsd:string"/>
      </xsd:sequence>
     </xsd:extension>
    </xsd:complexContent>
   </xsd:complexType>
   <xsd:complexType name="location">
    <xsd:sequence>
     <xsd:element name="latitude" type="xsd:double"/>
     <xsd:element name="longitude" type="xsd:double"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:element name="CreateCase">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="caseRequestWrapperObj" type="tns:caseRequestWrapper" nillable="true"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="CreateCaseResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="result" type="tns:caseResponseWrapper" nillable="true"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
  </xsd:schema>
 </types>
 <!-- Message for the header parts -->
 <message name="Header">
  <part name="AllowFieldTruncationHeader" element="tns:AllowFieldTruncationHeader"/>
  <part name="CallOptions" element="tns:CallOptions"/>
  <part name="DebuggingHeader" element="tns:DebuggingHeader"/>
  <part name="DebuggingInfo" element="tns:DebuggingInfo"/>
  <part name="SessionHeader" element="tns:SessionHeader"/>
 </message>
 <!-- Operation Messages -->
 <message name="CreateCaseRequest">
  <part element="tns:CreateCase" name="parameters"/>
 </message>
 <message name="CreateCaseResponse">
  <part element="tns:CreateCaseResponse" name="parameters"/>
 </message>
 <portType name="CaseWebServicePortType">
  <operation name="CreateCase">
   <input message="tns:CreateCaseRequest"/>
   <output message="tns:CreateCaseResponse"/>
  </operation>
 </portType>
 <binding name="CaseWebServiceBinding" type="tns:CaseWebServicePortType">
  <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="CreateCase">
   <soap:operation soapAction=""/>
   <input>
    <soap:header use="literal" part="SessionHeader" message="tns:Header"/>
    <soap:header use="literal" part="CallOptions" message="tns:Header"/>
    <soap:header use="literal" part="DebuggingHeader" message="tns:Header"/>
    <soap:header use="literal" part="AllowFieldTruncationHeader" message="tns:Header"/>
    <soap:body use="literal" parts="parameters"/>
   </input>
   <output>
    <soap:header use="literal" part="DebuggingInfo" message="tns:Header"/>
    <soap:body use="literal"/>
   </output>
  </operation>
 </binding>
 <service name="CaseWebServiceService">
  <documentation/>
  <port binding="tns:CaseWebServiceBinding" name="CaseWebService">
   <soap:address location="https://usa262s.sfdc-lywfpd.salesforce.com/services/Soap/class/CaseWebService"/>
  </port>
 </service>
</definitions>